CoffeeShop/Controllers/BillsController.cs
using CoffeeShop.Models; // Required for SqlConnection, SqlCommand, SqlDataReader
using CoffeeShop.Services;
using Microsoft.AspNetCore.Mvc;
using System.Data; // Required for CommandType and DataTable
using System.Data.SqlClient;

namespace CoffeeShop.Controllers
{
    [CheckAccess]
    public class BillsController : Controller
    {
        private readonly DatabaseService _databaseService;
        private readonly IConfiguration _configuration;

        // Single constructor to inject both DatabaseService and IConfiguration
        public BillsController(DatabaseService databaseService, IConfiguration configuration)
        {
            _databaseService = databaseService;
            _configuration = configuration;
        }

        #region AddEdit
        public IActionResult BillsAddEdit(int BillID)
        {
            string connectionString = this._configuration.GetConnectionString("ConnectionString");

            #region OrderDropDown
            ViewBag.OrderList = _databaseService.GetOrderDropDown();
            #endregion

            #region UserDropDown
            ViewBag.UserList = _databaseService.GetUserDropDown();
            #endregion

            #region BillByID

            BillsModel billsModel = new BillsModel();

            if (BillID > 0)
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (SqlCommand command = connection.CreateCommand())
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.CommandText = "PR_Bill_GetByID";
                        command.Parameters.AddWithValue("@BillID", BillID);

                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            DataTable table = new DataTable();
                            table.Load(reader);

                            if (table.Rows.Count > 0)
                            {
                                DataRow dataRow = table.Rows[0];
                                billsModel.BillNumber = dataRow["BillNumber"].ToString();
                                billsModel.BillDate = Convert.ToDateTime(dataRow["BillDate"]);
                                billsModel.OrderID = Convert.ToInt32(dataRow["OrderID"]);
                                billsModel.TotalAmount = Convert.ToDouble(dataRow["TotalAmount"]);
                                billsModel.Discount = dataRow["Discount"] != DBNull.Value ? Convert.ToDouble(dataRow["Discount"]) : (double?)null;
                                billsModel.NetAmount = Convert.ToDouble(dataRow["NetAmount"]);
                                billsModel.UserID = Convert.ToInt32(dataRow["UserID"]);
                            }
                        }
                    }
                }
                ViewBag.IsEdit = true; // Set flag to indicate edit mode
            }
            else
            {
                ViewBag.IsEdit = false; // Set flag to indicate add mode
            }

            return View("BillsAddEdit", billsModel);
            #endregion
        }
        #endregion

        #region SaveMethod
        public IActionResult BillsSave(BillsModel billsModel)
        {

            string connectionString = this._configuration.GetConnectionString("ConnectionString");
            SqlConnection connection = new SqlConnection(connectionString);
            connection.Open();
            SqlCommand command = connection.CreateCommand();
            command.CommandType = CommandType.StoredProcedure;
            if (billsModel.BillID == 0)
            {
                command.CommandText = "PR_Bill_Insert";
            }
            else
            {
                command.CommandText = "PR_Bill_Update";
                command.Parameters.Add("@BillID", SqlDbType.Int).Value = billsModel.BillID;
            }
            command.Parameters.Add("@BillNumber", SqlDbType.VarChar).Value = billsModel.BillNumber;
            command.Parameters.Add("@BillDate", SqlDbType.DateTime).Value = billsModel.BillDate;
            command.Parameters.Add("@OrderID", SqlDbType.Int).Value = billsModel.OrderID;
            command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = billsModel.TotalAmount;
            command.Parameters.Add("@Discount", SqlDbType.Decimal).Value = (object)billsModel.Discount ?? DBNull.Value;
            command.Parameters.Add("@NetAmount", SqlDbType.Decimal).Value = billsModel.NetAmount;
            command.Parameters.Add("@UserID", SqlDbType.Int).Value = billsModel.UserID;

            command.ExecuteNonQuery();
            return RedirectToAction("BillsAddEdit", new { BillID = billsModel.BillID });

        }
        #endregion



        public IActionResult BillsList()
        {
            DataTable billsTable = _databaseService.GetAllProcedure("PR_Bill_GetAll");
            return View(billsTable);
        }

        public IActionResult Delete(int ID)
        {
            try
            {
                // Use the database service to delete the order detail
                _databaseService.DeleteProcedure("PR_Bill_Delete", "BillID", ID);
                return Json(new { success = true, message = "Bills deleted successfully." });
            }
            catch (SqlException ex)
            {
                if (ex.Number == 547) // Foreign key violation error code in SQL Server
                {
                    return Json(new { success = false, message = "Unable to delete Bill. The Bill is referenced by other records." });
                }
                return Json(new { success = false, message = "An error occurred while deleting the Bill." });
            }
        }


    }
}

CoffeeShop/Views/Bills/BillsAddEdit.cshtml
@model CoffeeShop.Models.BillsModel;

@{
ViewData["Title"] = "Bill Form";
}

<main id="main" class="main">

    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <h5 class="card-title">Add Bill</h5>
                <button type="button" class="btn btn-danger" onclick="navigateToAdd('@Url.Action("BillsList", "Bills")')">x</button>
            </div>

            <!-- Vertical Form -->
            <form class="row g-3" method="post" asp-controller="Bills" asp-action="BillsSave">
                <input type="hidden" asp-for="BillID" />

                <div class="col-12">
                    <label asp-for="BillNumber" class="form-label">Bill Number</label>
                    <input type="text" class="form-control" asp-for="BillNumber" />
                    <span asp-validation-for="BillNumber" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label asp-for="BillDate" class="form-label">Bill Date</label>
                    <input type="date" class="form-control" asp-for="BillDate" />
                    <span asp-validation-for="BillDate" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label asp-for="OrderID" class="form-label">Order Date</label>
                    <select asp-for="OrderID" class="form-control" style="width: 250px; height: 35px; padding: 5px; font-size:14px; color: #555; border: 1px solid #ccc; border-radius: 4px;">
                        <option value="">Select OrderDate</option>
                        @foreach (var order in ViewBag.OrderList)
                        {
                            <option value="@order.OrderID">@order.OrderDate.ToShortDateString()</option>
                        }
                    </select>
                    <span asp-validation-for="OrderID" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label asp-for="TotalAmount" class="form-label">Total Amount</label>
                    <input type="number" class="form-control" asp-for="TotalAmount" step="0.01" />
                    <span asp-validation-for="TotalAmount" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label asp-for="Discount" class="form-label">Discount</label>
                    <input type="number" class="form-control" asp-for="Discount" step="0.01" />
                    <span asp-validation-for="Discount" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label asp-for="NetAmount" class="form-label">Net Amount</label>
                    <input type="number" class="form-control" asp-for="NetAmount" step="0.01" />
                    <span asp-validation-for="NetAmount" class="text-danger"></span>
                </div>

                <div class="col-12">
                    <label asp-for="UserID" class="form-label">UserName</label>
                    <select asp-for="UserID" class="form-control" style="width: 250px; height: 35px; padding: 5px; font-size:14px; color: #555; border: 1px solid #ccc; border-radius: 4px;">
                        <option value="">Select UserName</option>
                        @foreach (var user in ViewBag.UserList)
                        {
                            <option value="@user.UserID">@user.UserName</option>
                        }
                    </select>
                    <span asp-validation-for="UserID" class="text-danger"></span>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary">
                        @if (ViewBag.IsEdit)
                        {
                            <text>Update</text>
                        }
                        else
                        {
                            <text>Submit</text>
                        }
                    </button>
                    <button type="reset" class="btn btn-secondary">Reset</button>
                </div>
            </form><!-- Vertical Form -->


        </div>
    </div>

</main>

<script src="~/assets/js/scripts.js"></script>

CoffeeShop/Views/Bills/BillsList.cshtml
@model System.Data.DataTable

<main id="main" class="main">

    <div class="pagetitle">
        <h1>Bills Tables</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item">Tables</li>
                <li class="breadcrumb-item active">Bills</li>
            </ol>
            <a class="btn btn-primary" asp-controller="Bills" asp-action="BillsAddEdit" asp-route-BillID="0">Add</a>
        </nav>
    </div><!-- End Page Title -->

    <div class="card">
        <div class="card-body table-responsive">


            <!-- Default Table -->

            <table class="table">
                <thead>
                <tr>
                    @foreach (System.Data.DataColumn column in Model.Columns)
                    {
                    <th scope="col">@column.ColumnName</th>
                    }
                    <th scope="col" colspan="2" class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach (System.Data.DataRow row in Model.Rows)
                {
                <tr>
                    @foreach (var item in row.ItemArray)
                    {
                    <td>@item</td>
                    }
                    <td>
                        <a class="btn btn-primary" asp-controller="Bills" asp-action="BillsAddEdit" asp-route-BillID="@row["BillID"]">Edit</a>
                    </td>
                    <td>
                                <button class="btn btn-outline-danger btn-xs" onclick="deleteBill(@row["BillID"])">
                                    Delete
                                </button>
                    </td>
                </tr>
                }
                </tbody>
            </table>

            <!-- End Default Table Example -->
        </div>
    </div>
</main>

<script src="~/assets/js/scripts.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    function deleteBill(BillID) {
        if (confirm("Are you sure you want to delete this Bill?")) {
            $.ajax({
                url: '/Bills/Delete/' + BillID, // Adjust the URL if necessary
                type: 'POST',
                success: function (response) {
                    if (response.success) {
                        showSuccessMessage(response.message); // Show success message
                        location.reload(); // Optionally reload the page
                    } else {
                        showErrorMessage(response.message); // Show error message
                    }
                },
                error: function () {
                    showErrorMessage("An error occurred while processing the request."); // Fallback error message
                }
            });
        }
    }

    function showSuccessMessage(message) {
        var popup = $('<div class="success-popup"></div>').text(message);
        $('body').append(popup);

        popup.css({
            'position': 'fixed',
            'top': '20px',
            'right': '20px',
            'padding': '10px',
            'background-color': '#4CAF50', // Green background for success
            'color': '#fff',
            'border-radius': '5px',
            'font-size': '14px',
            'z-index': '1000'
        });

        setTimeout(function () {
            popup.fadeOut(500, function () {
                $(this).remove();
            });
        }, 3000);
    }

    function showErrorMessage(message) {
        var popup = $('<div class="error-popup"></div>').text(message);
        $('body').append(popup);

        popup.css({
            'position': 'fixed',
            'top': '20px',
            'right': '20px',
            'padding': '10px',
            'background-color': '#f44336', // Red background for error
            'color': '#fff',
            'border-radius': '5px',
            'font-size': '14px',
            'z-index': '1000'
        });

        setTimeout(function () {
            popup.fadeOut(500, function () {
                $(this).remove();
            });
        }, 3000);
    }
</script>